package com.myra.ai.coder

import android.util.Base64
import com.myra.ai.data.SecureStorage
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject
import java.io.OutputStreamWriter
import java.net.HttpURLConnection
import java.net.URL
import java.nio.charset.StandardCharsets

class GitHubManager(private val secureStorage: SecureStorage) {

    fun getGitHubToken(): String? {
        return secureStorage.getString("GITHUB_TOKEN")
    }

    fun saveGitHubToken(token: String) {
        secureStorage.saveString("GITHUB_TOKEN", token)
    }

    suspend fun createRepository(repoName: String, description: String = "Generated by Myra AI"): Result<String> = withContext(Dispatchers.IO) {
        val token = getGitHubToken()
        if (token.isNullBrandedToken()) {
            return@withContext Result.failure(Exception("GitHub token is missing in Settings."))
        }
        try {
            val url = URL("https://api.github.com/user/repos")
            val conn = url.openConnection() as HttpURLConnection
            conn.requestMethod = "POST"
            conn.setRequestProperty("Authorization", "Bearer $token")
            conn.setRequestProperty("Accept", "application/vnd.github.v3+json")
            conn.setRequestProperty("Content-Type", "application/json")
            conn.doOutput = true

            val jsonPayload = JSONObject().apply {
                put("name", repoName)
                put("description", description)
                put("private", false)
                put("auto_init", true)
            }

            OutputStreamWriter(conn.outputStream).use { writer ->
                writer.write(jsonPayload.toString())
            }

            val responseCode = conn.responseCode
            if (responseCode == 201 || responseCode == 200) {
                val responseText = conn.inputStream.bufferedReader().readText()
                val json = JSONObject(responseText)
                val htmlUrl = json.getString("html_url")
                Result.success(htmlUrl)
            } else {
                val errText = conn.errorStream?.bufferedReader()?.readText() ?: "HTTP $responseCode"
                Result.failure(Exception("Failed to create GitHub repo: $errText"))
            }
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    suspend fun createFileOrUpdate(
        owner: String,
        repo: String,
        filePath: String,
        content: String,
        commitMessage: String = "Add $filePath via Myra AI"
    ): Result<Boolean> = withContext(Dispatchers.IO) {
        val token = getGitHubToken()
        if (token.isNullBrandedToken()) {
            return@withContext Result.failure(Exception("GitHub token is missing."))
        }
        try {
            val url = URL("https://api.github.com/repos/$owner/$repo/contents/$filePath")
            val conn = url.openConnection() as HttpURLConnection
            conn.requestMethod = "PUT"
            conn.setRequestProperty("Authorization", "Bearer $token")
            conn.setRequestProperty("Accept", "application/vnd.github.v3+json")
            conn.setRequestProperty("Content-Type", "application/json")
            conn.doOutput = true

            val base64Content = Base64.encodeToString(content.toByteArray(StandardCharsets.UTF_8), Base64.NO_WRAP)

            val jsonPayload = JSONObject().apply {
                put("message", commitMessage)
                put("content", base64Content)
            }

            OutputStreamWriter(conn.outputStream).use { writer ->
                writer.write(jsonPayload.toString())
            }

            val responseCode = conn.responseCode
            if (responseCode == 200 || responseCode == 201) {
                Result.success(true)
            } else {
                val errText = conn.errorStream?.bufferedReader()?.readText() ?: "HTTP $responseCode"
                Result.failure(Exception("Failed to push file $filePath: $errText"))
            }
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    private fun String?.isNullBrandedToken(): Boolean {
        return this.isNullOrBlank()
    }
}
